/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

import javax.swing.*;
import metier.Produit ;

import java.awt.*;
import java.util.*;
import metier.Produit;
import java.lang.Enum ;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author sami
 */
public class FenAccueil extends javax.swing.JFrame {
    int ligneChoisie;
    int colonneChoisie;
    private final DefaultListModel boucle;
    private final DefaultListModel montre;
    private final DefaultListModel bracelet;
    private final DefaultListModel bague;
    private final DefaultListModel alliance;
    
    public FenAccueil() {
        
        
        boucle= new DefaultListModel();
        montre = new DefaultListModel();
        bracelet = new DefaultListModel();
        bague = new DefaultListModel();
        alliance = new DefaultListModel();

        String[] lesAlliances = {"Or jaune", "Or blanc", "Or rose"};
        int i=0;
        for (i = 0; i < lesAlliances.length; i++) {
            alliance.addElement(lesAlliances[i]);
        }
        
        String[] lesMontres = {"Analogique", "Chrono", "Submariner","Retro","Gousset"};
        int j=0;
        for (j = 0; j < lesMontres.length; j++) {
            montre.addElement(lesMontres[j]);
        }
        
        String[] lesBagues = {"Diamant", "Emeraude", "Rubis"};
        int m=0;
        for (m= 0; m < lesBagues.length; m++) {
            bague.addElement(lesBagues[m]);
        }
        
         
        initComponents();
        String row1[]={"1", "Splendeur","Bague","Or Jaune","1","1000","Vers un mariage réussi"};
         String row2[]={"2", "Beauté","Bague","Or Blanc","1","1200","Réel engagement"};
         String row3[]={"3", "Mon précieux","Bague","Or Rose","1","1500","Golumm Goloum"};
         
         DefaultTableModel tableModel=(DefaultTableModel) tableProduit.getModel();
          tableModel.addRow(row1);
          tableModel.addRow(row2);
          tableModel.addRow(row3);
        
        
        
        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jt_produits = new javax.swing.JPanel();
        jp_recherche_prod = new javax.swing.JPanel();
        lbl_titre_jp1 = new javax.swing.JLabel();
        lbl_prod1 = new javax.swing.JLabel();
        tf_libelle1 = new javax.swing.JTextField();
        lbl_cat1 = new javax.swing.JLabel();
        cb_cat1 = new javax.swing.JComboBox<>();
        lbl_sous_cat1 = new javax.swing.JLabel();
        lbl_id1 = new javax.swing.JLabel();
        tf_id1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jscroll_prod1 = new javax.swing.JScrollPane();
        jtable_prod1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nomProduit = new javax.swing.JLabel();
        saisieId = new javax.swing.JTextField();
        saisieNom = new javax.swing.JTextField();
        idProduit = new javax.swing.JLabel();
        categorieProduit = new javax.swing.JLabel();
        saisieCategorie = new javax.swing.JTextField();
        sousCategorieProduit = new javax.swing.JLabel();
        saisieSousCategorie = new javax.swing.JTextField();
        promoProduit = new javax.swing.JLabel();
        saisiePromo = new javax.swing.JTextField();
        prixProduit = new javax.swing.JLabel();
        saisiePrix = new javax.swing.JTextField();
        descriptionProduit = new javax.swing.JLabel();
        saisieDescription = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduit = new javax.swing.JTable();
        boutonSupprimer = new javax.swing.JButton();
        boutonAjouter = new javax.swing.JButton();
        boutonModifier = new javax.swing.JButton();
        nouvelleValeurCellule = new javax.swing.JLabel();
        saisieNouvelleValeur = new javax.swing.JTextField();
        jt_cat = new javax.swing.JPanel();
        jt_promo = new javax.swing.JPanel();
        jt_clients = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIJOUTERIE ALMASS");

        jt_produits.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jp_recherche_prod.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_titre_jp1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbl_titre_jp1.setForeground(new java.awt.Color(51, 51, 51));
        lbl_titre_jp1.setText("Rechercher un produit");

        lbl_prod1.setText("Libellé");

        tf_libelle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_libelle1ActionPerformed(evt);
            }
        });

        lbl_cat1.setText("Catégorie");

        cb_cat1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {" ", "Boucle","Montre", "Bracelet", "Bague", "Alliance" }));
        cb_cat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_cat1ActionPerformed(evt);
            }
        });

        lbl_sous_cat1.setText("Sous-Catégorie");

        lbl_id1.setText("ID :");

        tf_id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_id1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "selection sous catégorie" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jtable_prod1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtable_prod1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Libellé", "Catégorie ", "Sous-Catégorie", "Promo: ", "Prix", "Taux Promo", "Prix Réduit", "Visible"
            }
        ));
        jtable_prod1.setColumnSelectionAllowed(true);
        jtable_prod1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtable_prod1.setShowGrid(true);
        jscroll_prod1.setViewportView(jtable_prod1);
        jtable_prod1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtable_prod1.getColumnModel().getColumnCount() > 0) {
            jtable_prod1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jtable_prod1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jtable_prod1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jtable_prod1.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtable_prod1.getColumnModel().getColumn(8).setPreferredWidth(10);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Crud Produits");

        nomProduit.setText("nom Produit");

        idProduit.setText("id");

        categorieProduit.setText("Catégorie");

        sousCategorieProduit.setText("Sous Catégorie");

        promoProduit.setText("Promo");

        prixProduit.setText("Prix");

        descriptionProduit.setText("Description");

        tableProduit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nom", "Catégorie", "Sous Catégorie", "Promo", "Prix", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProduit.setColumnSelectionAllowed(true);
        tableProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProduitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProduit);
        tableProduit.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        boutonSupprimer.setText("SUPPRIMER");
        boutonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSupprimerActionPerformed(evt);
            }
        });

        boutonAjouter.setText("AJOUTER");
        boutonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjouterActionPerformed(evt);
            }
        });

        boutonModifier.setText("MODIFIER");
        boutonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonModifierActionPerformed(evt);
            }
        });

        nouvelleValeurCellule.setText("nouvelle Valeur");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prixProduit, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                    .addComponent(idProduit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(saisieId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(91, 91, 91)
                                        .addComponent(nomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saisieNom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(107, 107, 107)
                                        .addComponent(categorieProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(saisieCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(sousCategorieProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(saisieSousCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(promoProduit)
                                        .addGap(26, 26, 26)
                                        .addComponent(saisiePromo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(saisiePrix, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78)
                                        .addComponent(descriptionProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(saisieDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nouvelleValeurCellule, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(saisieNouvelleValeur, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(boutonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(boutonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(boutonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saisieId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idProduit)
                    .addComponent(nomProduit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saisieNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categorieProduit)
                    .addComponent(saisieCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sousCategorieProduit)
                    .addComponent(saisieSousCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(promoProduit)
                    .addComponent(saisiePromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prixProduit)
                    .addComponent(saisiePrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionProduit)
                    .addComponent(saisieDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nouvelleValeurCellule)
                    .addComponent(saisieNouvelleValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonSupprimer)
                    .addComponent(boutonModifier)
                    .addComponent(boutonAjouter))
                .addGap(237, 237, 237))
        );

        javax.swing.GroupLayout jp_recherche_prodLayout = new javax.swing.GroupLayout(jp_recherche_prod);
        jp_recherche_prod.setLayout(jp_recherche_prodLayout);
        jp_recherche_prodLayout.setHorizontalGroup(
            jp_recherche_prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_recherche_prodLayout.createSequentialGroup()
                .addGroup(jp_recherche_prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_recherche_prodLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jp_recherche_prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jscroll_prod1)
                            .addGroup(jp_recherche_prodLayout.createSequentialGroup()
                                .addGroup(jp_recherche_prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_titre_jp1)
                                    .addGroup(jp_recherche_prodLayout.createSequentialGroup()
                                        .addComponent(lbl_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_libelle1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(267, 267, 267))
                            .addGroup(jp_recherche_prodLayout.createSequentialGroup()
                                .addComponent(lbl_cat1)
                                .addGap(26, 26, 26)
                                .addComponent(cb_cat1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(lbl_sous_cat1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_recherche_prodLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jp_recherche_prodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_recherche_prodLayout.setVerticalGroup(
            jp_recherche_prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_recherche_prodLayout.createSequentialGroup()
                .addComponent(lbl_titre_jp1)
                .addGap(6, 6, 6)
                .addGroup(jp_recherche_prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_prod1)
                    .addComponent(tf_libelle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id1)
                    .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_recherche_prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_recherche_prodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_cat1)
                        .addComponent(cb_cat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_sous_cat1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jscroll_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jt_produitsLayout = new javax.swing.GroupLayout(jt_produits);
        jt_produits.setLayout(jt_produitsLayout);
        jt_produitsLayout.setHorizontalGroup(
            jt_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jt_produitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_recherche_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 1325, Short.MAX_VALUE)
                .addContainerGap())
        );
        jt_produitsLayout.setVerticalGroup(
            jt_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jt_produitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_recherche_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1408, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Produits", jt_produits);

        javax.swing.GroupLayout jt_catLayout = new javax.swing.GroupLayout(jt_cat);
        jt_cat.setLayout(jt_catLayout);
        jt_catLayout.setHorizontalGroup(
            jt_catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1351, Short.MAX_VALUE)
        );
        jt_catLayout.setVerticalGroup(
            jt_catLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2493, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Catégories", jt_cat);

        javax.swing.GroupLayout jt_promoLayout = new javax.swing.GroupLayout(jt_promo);
        jt_promo.setLayout(jt_promoLayout);
        jt_promoLayout.setHorizontalGroup(
            jt_promoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1351, Short.MAX_VALUE)
        );
        jt_promoLayout.setVerticalGroup(
            jt_promoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2493, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Promotions", jt_promo);

        javax.swing.GroupLayout jt_clientsLayout = new javax.swing.GroupLayout(jt_clients);
        jt_clients.setLayout(jt_clientsLayout);
        jt_clientsLayout.setHorizontalGroup(
            jt_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1351, Short.MAX_VALUE)
        );
        jt_clientsLayout.setVerticalGroup(
            jt_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2493, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Clients", jt_clients);

        getContentPane().add(jTabbedPane, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_id1ActionPerformed

    private void cb_cat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_cat1ActionPerformed

         if (cb_cat1.getSelectedItem().equals("Alliance")) {
            jList1.setModel(alliance);
            if (alliance.isEmpty()) {
                jScrollPane3.setVisible(false);
                lbl_sous_cat1.setVisible(false);
                
            } 
            else {
                jScrollPane3.setVisible(true);
                lbl_sous_cat1.setVisible(true);
            }
        }
        if (cb_cat1.getSelectedItem().equals("Montre")) {
            jList1.setModel(montre);
            if (montre.isEmpty()) {
                jScrollPane3.setVisible(false);
                
                lbl_sous_cat1.setVisible(false);

            } else {
                jScrollPane3.setVisible(true);
                
                lbl_sous_cat1.setVisible(true);

            }
        }
        if (cb_cat1.getSelectedItem().equals("Bague")) {
            jList1.setModel(bague);
            if (bague.isEmpty()) {
                jScrollPane3.setVisible(false);
                
                lbl_sous_cat1.setVisible(false);

            } else {
                jScrollPane3.setVisible(true);
                
                lbl_sous_cat1.setVisible(true);

            }
        }
          if (cb_cat1.getSelectedItem().equals("Bracelet")) {
            jList1.setModel(bracelet);
            if (bracelet.isEmpty()) {
                jScrollPane3.setVisible(false);
                
                lbl_sous_cat1.setVisible(false);

            } else {
                jScrollPane3.setVisible(true);
                
                lbl_sous_cat1.setVisible(true);

            }
        }
           if (cb_cat1.getSelectedItem().equals("Boucle")) {
            jList1.setModel(boucle);
            if (boucle.isEmpty()) {
                jScrollPane3.setVisible(false);
                
                lbl_sous_cat1.setVisible(false);

            } else {
                jScrollPane3.setVisible(true);
                
                lbl_sous_cat1.setVisible(true);

            }
        }
    
      
          
    }//GEN-LAST:event_cb_cat1ActionPerformed

    private void tf_libelle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_libelle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_libelle1ActionPerformed

    private void boutonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjouterActionPerformed
            if ( saisieId.getText().equals("") ||
                  saisieCategorie.getText().equals("") ||
                  saisieDescription.getText().equals("") ||
                  saisieNom.getText().equals("") ||
                  saisiePromo.getText().equals("") ||
                  saisieSousCategorie.getText().equals("") ||
                  saisiePrix.getText().equals("") 
                )
            {
                JOptionPane.showMessageDialog(this, " toutes les caractéristiques n'ont pas été correctement entrées");
            }
            else {
                String data[]={saisieId.getText(),saisieNom.getText(),saisieCategorie.getText(),saisieSousCategorie.getText(),saisiePromo.getText(),saisiePrix.getText(),saisieDescription.getText()};
                DefaultTableModel tableModel=(DefaultTableModel) tableProduit.getModel();
                tableModel.addRow(data);
                JOptionPane.showMessageDialog(this, " Le produit a bien été ajouté ! ");
                saisieId.setText("");
                saisieNom.setText("");
                saisieCategorie.setText("");
                saisieSousCategorie.setText("");
                saisiePromo.setText("");
                saisiePrix.setText("");
                saisieDescription.setText("");
                
            }
    }//GEN-LAST:event_boutonAjouterActionPerformed

    private void tableProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProduitMouseClicked
        ligneChoisie = tableProduit.getSelectedRow();
        colonneChoisie= tableProduit.getSelectedColumn();
    }//GEN-LAST:event_tableProduitMouseClicked

    private void boutonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSupprimerActionPerformed
     DefaultTableModel tableModel=(DefaultTableModel) tableProduit.getModel();
     tableModel.removeRow(ligneChoisie);
    }//GEN-LAST:event_boutonSupprimerActionPerformed

    private void boutonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonModifierActionPerformed
        DefaultTableModel tableModel=(DefaultTableModel) tableProduit.getModel();
         if ( saisieNouvelleValeur.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, " Veuillez bien rentrer une nouvelle valeur pour la cellule à modofier svp");
            }
         else {
             tableModel.setValueAt(saisieNouvelleValeur.getText(), ligneChoisie, colonneChoisie);
         }
    }//GEN-LAST:event_boutonModifierActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAjouter;
    private javax.swing.JButton boutonModifier;
    private javax.swing.JButton boutonSupprimer;
    private javax.swing.JLabel categorieProduit;
    private javax.swing.JComboBox<String> cb_cat1;
    private javax.swing.JLabel descriptionProduit;
    private javax.swing.JLabel idProduit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel jp_recherche_prod;
    private javax.swing.JScrollPane jscroll_prod1;
    private javax.swing.JPanel jt_cat;
    private javax.swing.JPanel jt_clients;
    private javax.swing.JPanel jt_produits;
    private javax.swing.JPanel jt_promo;
    private javax.swing.JTable jtable_prod1;
    private javax.swing.JLabel lbl_cat1;
    private javax.swing.JLabel lbl_id1;
    private javax.swing.JLabel lbl_prod1;
    private javax.swing.JLabel lbl_sous_cat1;
    private javax.swing.JLabel lbl_titre_jp1;
    private javax.swing.JLabel nomProduit;
    private javax.swing.JLabel nouvelleValeurCellule;
    private javax.swing.JLabel prixProduit;
    private javax.swing.JLabel promoProduit;
    private javax.swing.JTextField saisieCategorie;
    private javax.swing.JTextField saisieDescription;
    private javax.swing.JTextField saisieId;
    private javax.swing.JTextField saisieNom;
    private javax.swing.JTextField saisieNouvelleValeur;
    private javax.swing.JTextField saisiePrix;
    private javax.swing.JTextField saisiePromo;
    private javax.swing.JTextField saisieSousCategorie;
    private javax.swing.JLabel sousCategorieProduit;
    private javax.swing.JTable tableProduit;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JTextField tf_libelle1;
    // End of variables declaration//GEN-END:variables
}
